/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Account;
import org.openapitools.model.AmountRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-11T17:51:57.836378400+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "accounts", description = "the accounts API")
public interface AccountsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /accounts/{id} : Удалить счёт
     *
     * @param id  (required)
     * @return Счёт успешно удалён (status code 200)
     *         or Счёт не найден (status code 404)
     */
    @Operation(
        operationId = "accountsIdDelete",
        summary = "Удалить счёт",
        responses = {
            @ApiResponse(responseCode = "200", description = "Счёт успешно удалён"),
            @ApiResponse(responseCode = "404", description = "Счёт не найден")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/accounts/{id}"
    )
    
    default ResponseEntity<Void> accountsIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /accounts/{id}/deposit : Пополнить счёт
     *
     * @param id  (required)
     * @param amountRequest  (required)
     * @return Счёт успешно пополнен (status code 200)
     *         or Некорректный запрос (status code 400)
     *         or Счёт не найден (status code 404)
     */
    @Operation(
        operationId = "accountsIdDepositPost",
        summary = "Пополнить счёт",
        responses = {
            @ApiResponse(responseCode = "200", description = "Счёт успешно пополнен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Account.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректный запрос"),
            @ApiResponse(responseCode = "404", description = "Счёт не найден")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/accounts/{id}/deposit",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Account> accountsIdDepositPost(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "AmountRequest", description = "", required = true) @Valid @RequestBody AmountRequest amountRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ownerName\" : \"ownerName\", \"balance\" : 6.027456183070403, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /accounts/{id} : Получить информацию о счёте
     *
     * @param id  (required)
     * @return Успешный ответ (status code 200)
     *         or Счёт не найден (status code 404)
     */
    @Operation(
        operationId = "accountsIdGet",
        summary = "Получить информацию о счёте",
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Account.class))
            }),
            @ApiResponse(responseCode = "404", description = "Счёт не найден")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Account> accountsIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ownerName\" : \"ownerName\", \"balance\" : 6.027456183070403, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /accounts/{id}/withdraw : Снять средства со счёта
     *
     * @param id  (required)
     * @param amountRequest  (required)
     * @return Средства успешно сняты (status code 200)
     *         or Некорректный запрос (status code 400)
     *         or Счёт не найден (status code 404)
     */
    @Operation(
        operationId = "accountsIdWithdrawPost",
        summary = "Снять средства со счёта",
        responses = {
            @ApiResponse(responseCode = "200", description = "Средства успешно сняты", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Account.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректный запрос"),
            @ApiResponse(responseCode = "404", description = "Счёт не найден")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/accounts/{id}/withdraw",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Account> accountsIdWithdrawPost(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "AmountRequest", description = "", required = true) @Valid @RequestBody AmountRequest amountRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ownerName\" : \"ownerName\", \"balance\" : 6.027456183070403, \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
